USE [master]
GO

/****** Object:  Database [TareaAnalisis]    Script Date: 02/02/2019 9:15:33 ******/
CREATE DATABASE [TareaAnalisis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TareaAnalisis', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.NOEXPRESS\MSSQL\DATA\TareaAnalisis.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TareaAnalisis_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.NOEXPRESS\MSSQL\DATA\TareaAnalisis_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TareaAnalisis] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TareaAnalisis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TareaAnalisis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TareaAnalisis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TareaAnalisis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TareaAnalisis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TareaAnalisis] SET ARITHABORT OFF 
GO

ALTER DATABASE [TareaAnalisis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TareaAnalisis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TareaAnalisis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TareaAnalisis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TareaAnalisis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TareaAnalisis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TareaAnalisis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TareaAnalisis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TareaAnalisis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TareaAnalisis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TareaAnalisis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TareaAnalisis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TareaAnalisis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TareaAnalisis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TareaAnalisis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TareaAnalisis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TareaAnalisis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TareaAnalisis] SET RECOVERY FULL 
GO

ALTER DATABASE [TareaAnalisis] SET  MULTI_USER 
GO

ALTER DATABASE [TareaAnalisis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TareaAnalisis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TareaAnalisis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TareaAnalisis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TareaAnalisis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TareaAnalisis] SET QUERY_STORE = OFF
GO

USE [TareaAnalisis]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TareaAnalisis] SET  READ_WRITE 
GO


